// Static problem data seeded from WHO, UN, IEA, IPCC sources
export type Problem = {
  id: number;
  title: string;
  description: string;
  category: string;
  severity: number; // 1-10
  scope: "Local" | "Regional" | "Global";
  affectedPopulation: string;
  regions: string[];
  source: string;
};

export const CATEGORIES = [
  "Water & Sanitation",
  "Energy Access",
  "Climate Adaptation",
  "Food Security",
  "Air Quality",
  "Health Systems",
  "Urban Infrastructure",
  "Waste Management",
  "Biodiversity",
  "Ocean & Marine",
  "Transportation",
  "Housing",
  "Education Access",
  "Digital Divide",
  "Disaster Resilience",
  "Agricultural Tech",
  "Renewable Energy",
  "Carbon Capture",
  "Industrial Emissions",
  "Soil Degradation",
  "Noise Pollution",
  "Mental Health",
  "Maternal Health",
  "Water Scarcity",
  "Refugee Infrastructure",
  "Sustainable Mining",
] as const;

export const PROBLEMS: Problem[] = [
  {
    id: 1,
    title: "Arsenic Contamination in Bangladesh Groundwater",
    description: "An estimated 35-77 million people exposed to arsenic above WHO guidelines in Bangladesh's tube wells, causing skin lesions and cancers.",
    category: "Water & Sanitation",
    severity: 9,
    scope: "Regional",
    affectedPopulation: "77M",
    regions: ["South Asia"],
    source: "WHO",
  },
  {
    id: 2,
    title: "Lack of Clean Cooking Fuel in Sub-Saharan Africa",
    description: "Over 900M people rely on solid biomass for cooking, causing 4.3M premature deaths annually from household air pollution.",
    category: "Energy Access",
    severity: 9,
    scope: "Global",
    affectedPopulation: "900M",
    regions: ["Sub-Saharan Africa", "South Asia"],
    source: "IEA",
  },
  {
    id: 3,
    title: "Urban Heat Island Effect in Megacities",
    description: "Metropolitan areas experience 1-7°C higher temperatures than surrounding rural zones, worsening heat mortality and energy demand.",
    category: "Climate Adaptation",
    severity: 7,
    scope: "Local",
    affectedPopulation: "1.5B",
    regions: ["Global"],
    source: "IPCC",
  },
  {
    id: 4,
    title: "Post-Harvest Food Loss in Tropical Supply Chains",
    description: "30-40% of food produced in tropical regions spoils before reaching markets due to inadequate cold chain and storage infrastructure.",
    category: "Food Security",
    severity: 8,
    scope: "Regional",
    affectedPopulation: "500M",
    regions: ["Sub-Saharan Africa", "Southeast Asia"],
    source: "UN",
  },
  {
    id: 5,
    title: "Ambient PM2.5 Exceedance in Delhi NCR",
    description: "Annual average PM2.5 in Delhi exceeds WHO guidelines by over 10x, causing an estimated 30K premature deaths per year.",
    category: "Air Quality",
    severity: 9,
    scope: "Local",
    affectedPopulation: "30M",
    regions: ["South Asia"],
    source: "WHO",
  },
  {
    id: 6,
    title: "Rural Health Clinic Power Reliability",
    description: "Over 1B people served by health facilities with unreliable or no electricity, limiting vaccine storage and emergency care.",
    category: "Health Systems",
    severity: 8,
    scope: "Global",
    affectedPopulation: "1B",
    regions: ["Sub-Saharan Africa", "South Asia"],
    source: "WHO",
  },
  {
    id: 7,
    title: "Seawater Intrusion in Coastal Aquifers",
    description: "Rising sea levels and over-extraction are salinizing freshwater aquifers serving 200M+ coastal residents worldwide.",
    category: "Water Scarcity",
    severity: 8,
    scope: "Global",
    affectedPopulation: "200M",
    regions: ["Southeast Asia", "Small Island States"],
    source: "IPCC",
  },
  {
    id: 8,
    title: "E-Waste Recycling Without Worker Protections",
    description: "Informal e-waste processing in developing nations exposes workers and communities to lead, mercury, and dioxins without safeguards.",
    category: "Waste Management",
    severity: 7,
    scope: "Regional",
    affectedPopulation: "500K",
    regions: ["West Africa", "South Asia"],
    source: "UN",
  },
  {
    id: 9,
    title: "Coral Reef Bleaching and Coastal Protection Loss",
    description: "70-90% of coral reefs could disappear at 1.5°C warming, removing natural breakwaters and collapsing fisheries for 500M+ people.",
    category: "Ocean & Marine",
    severity: 9,
    scope: "Global",
    affectedPopulation: "500M",
    regions: ["Southeast Asia", "Pacific", "Caribbean"],
    source: "IPCC",
  },
  {
    id: 10,
    title: "Unreinforced Masonry Schools in Seismic Zones",
    description: "Millions of children attend schools built with unreinforced masonry in high-seismic regions, risking catastrophic collapse in earthquakes.",
    category: "Urban Infrastructure",
    severity: 8,
    scope: "Global",
    affectedPopulation: "175M",
    regions: ["South Asia", "Middle East", "Latin America"],
    source: "UN",
  },
  {
    id: 11,
    title: "Last-Mile Vaccine Delivery in Conflict Zones",
    description: "Cold chain breaks and access barriers prevent vaccine delivery to 19.7M zero-dose children in fragile and conflict-affected settings.",
    category: "Health Systems",
    severity: 8,
    scope: "Regional",
    affectedPopulation: "19.7M",
    regions: ["Sub-Saharan Africa", "Middle East"],
    source: "WHO",
  },
  {
    id: 12,
    title: "Microplastic Contamination in Drinking Water",
    description: "83% of tap water samples globally contain microplastic fibers; health impacts remain poorly understood and unregulated.",
    category: "Water & Sanitation",
    severity: 6,
    scope: "Global",
    affectedPopulation: "5B",
    regions: ["Global"],
    source: "WHO",
  },
  {
    id: 13,
    title: "Grid Instability from Variable Renewable Penetration",
    description: "Island and weak-grid systems face frequency instability beyond 30% renewable penetration without adequate storage or flexibility.",
    category: "Renewable Energy",
    severity: 7,
    scope: "Regional",
    affectedPopulation: "100M",
    regions: ["Small Island States", "Sub-Saharan Africa"],
    source: "IEA",
  },
  {
    id: 14,
    title: "Soil Salinization in Irrigated Arid Agriculture",
    description: "20% of irrigated land globally is salt-affected, reducing crop yields and threatening food production in arid regions.",
    category: "Soil Degradation",
    severity: 7,
    scope: "Regional",
    affectedPopulation: "1.5B",
    regions: ["Middle East", "Central Asia", "North Africa"],
    source: "UN",
  },
  {
    id: 15,
    title: "Informal Settlement Flood Vulnerability",
    description: "1B+ people in informal settlements lack drainage and face disproportionate flood damage, with minimal insurance or recovery support.",
    category: "Disaster Resilience",
    severity: 8,
    scope: "Global",
    affectedPopulation: "1B",
    regions: ["South Asia", "Sub-Saharan Africa", "Latin America"],
    source: "UN",
  },
  {
    id: 16,
    title: "Antibiotic Resistance in Wastewater Effluent",
    description: "Pharmaceutical residues and resistant bacteria in treated wastewater are spreading AMR through water reuse and environmental pathways.",
    category: "Water & Sanitation",
    severity: 7,
    scope: "Global",
    affectedPopulation: "700K",
    regions: ["Global"],
    source: "WHO",
  },
  {
    id: 17,
    title: "Diesel Generator Backup in Off-Grid Telecom",
    description: "Telecom towers in off-grid areas rely on diesel generators, producing 49M tonnes CO2/year and creating fuel supply vulnerabilities.",
    category: "Energy Access",
    severity: 6,
    scope: "Regional",
    affectedPopulation: "500M",
    regions: ["Sub-Saharan Africa", "South Asia"],
    source: "IEA",
  },
  {
    id: 18,
    title: "Bridge Infrastructure Gap in Rural Connectivity",
    description: "Over 1B people lack all-weather road access, and thousands of critical rural bridges are structurally deficient or missing entirely.",
    category: "Transportation",
    severity: 7,
    scope: "Global",
    affectedPopulation: "1B",
    regions: ["Sub-Saharan Africa", "South Asia", "Latin America"],
    source: "World Bank",
  },
  {
    id: 19,
    title: "Deforestation-Driven Zoonotic Spillover Risk",
    description: "Habitat fragmentation increases human-wildlife contact, raising zoonotic disease emergence risk by 2-3x in deforestation frontiers.",
    category: "Biodiversity",
    severity: 7,
    scope: "Regional",
    affectedPopulation: "3.3B",
    regions: ["Southeast Asia", "Sub-Saharan Africa", "Latin America"],
    source: "IPCC",
  },
  {
    id: 20,
    title: "Carbon Capture Scaling for Industrial Point Sources",
    description: "Current CCUS capacity captures only 0.1% of global emissions; scaling 100x by 2040 requires breakthrough cost and energy reduction.",
    category: "Carbon Capture",
    severity: 8,
    scope: "Global",
    affectedPopulation: "8B",
    regions: ["Global"],
    source: "IEA",
  },
  {
    id: 21,
    title: "Maternal Mortality in Remote Health Posts",
    description: "Sub-Saharan Africa accounts for 70% of global maternal deaths; remote health posts lack blood storage and emergency surgical capacity.",
    category: "Maternal Health",
    severity: 9,
    scope: "Regional",
    affectedPopulation: "200M",
    regions: ["Sub-Saharan Africa"],
    source: "WHO",
  },
  {
    id: 22,
    title: "Refugee Camp Wastewater Treatment Overload",
    description: "Large camps host 100K+ people with wastewater systems designed for 10K, causing groundwater contamination and disease outbreaks.",
    category: "Refugee Infrastructure",
    severity: 8,
    scope: "Local",
    affectedPopulation: "30M",
    regions: ["Middle East", "East Africa"],
    source: "UN",
  },
  {
    id: 23,
    title: "Noise Pollution and Cardiovascular Disease in Cities",
    description: "20% of EU population exposed to harmful noise levels; environmental noise contributes to 12K premature deaths annually in Europe alone.",
    category: "Noise Pollution",
    severity: 5,
    scope: "Local",
    affectedPopulation: "100M",
    regions: ["Europe", "East Asia"],
    source: "WHO",
  },
  {
    id: 24,
    title: "Affordable Housing Resilience Retrofit Gap",
    description: "90% of existing affordable housing in hurricane zones lacks wind/flood resilience, but retrofit costs exceed available subsidies by 3-5x.",
    category: "Housing",
    severity: 7,
    scope: "Regional",
    affectedPopulation: "300M",
    regions: ["Latin America", "Caribbean", "Southeast Asia"],
    source: "World Bank",
  },
  {
    id: 25,
    title: "Digital Exclusion in Agricultural Extension Services",
    description: "500M smallholder farmers lack digital access to weather, market, and agronomy data, perpetuating yield gaps of 40-60%.",
    category: "Digital Divide",
    severity: 6,
    scope: "Global",
    affectedPopulation: "500M",
    regions: ["Sub-Saharan Africa", "South Asia"],
    source: "UN",
  },
  {
    id: 26,
    title: "Industrial Heat Decarbonization Below 150°C",
    description: "40% of industrial energy demand is low-grade heat below 150°C — electrifiable with heat pumps but adoption remains below 5%.",
    category: "Industrial Emissions",
    severity: 7,
    scope: "Global",
    affectedPopulation: "2B",
    regions: ["Europe", "East Asia", "North America"],
    source: "IEA",
  },
  {
    id: 27,
    title: "Sustainable Cooling for Vaccine Cold Chains",
    description: "50% of vaccines are wasted globally due to cold chain breaks; solar-direct cooling could help but lacks standardization and scale.",
    category: "Health Systems",
    severity: 7,
    scope: "Global",
    affectedPopulation: "3B",
    regions: ["Sub-Saharan Africa", "South Asia"],
    source: "WHO",
  },
  {
    id: 28,
    title: "Precision Agriculture for Smallholder Farms",
    description: "Smallholders manage 80% of farms in developing regions but lack affordable sensors, AI tools, and connectivity for precision methods.",
    category: "Agricultural Tech",
    severity: 6,
    scope: "Regional",
    affectedPopulation: "2B",
    regions: ["Sub-Saharan Africa", "South Asia"],
    source: "UN",
  },
  {
    id: 29,
    title: "Methane Leak Detection in Aging Gas Infrastructure",
    description: "Methane leaks from aging pipelines and wells account for 5.8B tonnes CO2e; continuous monitoring technology is nascent and costly.",
    category: "Renewable Energy",
    severity: 8,
    scope: "Global",
    affectedPopulation: "5B",
    regions: ["North America", "Central Asia", "Middle East"],
    source: "IEA",
  },
  {
    id: 30,
    title: "Open-Pit Mine Rehabilitation and Water Quality",
    description: "Thousands of abandoned mines leach heavy metals into watersheds; rehabilitation costs exceed $50B globally with current technology.",
    category: "Sustainable Mining",
    severity: 7,
    scope: "Regional",
    affectedPopulation: "100M",
    regions: ["Latin America", "Sub-Saharan Africa", "Oceania"],
    source: "UN",
  },
];
